%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.1

-ifndef(any_pb).
-define(any_pb, true).

-define(any_pb_gpb_version, "4.19.1").

-ifndef('ANY_PB_H').
-define('ANY_PB_H', true).
-record('Any',
    % = 1, optional
    {
        type_url = [] :: unicode:chardata() | undefined,
        % = 2, optional
        value = <<>> :: iodata() | undefined
    }
).
-endif.

-endif.
