%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.1

-ifndef(any_pb).
-define(any_pb, true).

-define(any_pb_gpb_version, "4.19.1").

-ifndef('ANY_PB_H').
-define('ANY_PB_H', true).
-record('Any',
        {type_url = []          :: unicode:chardata() | undefined, % = 1, optional
         value = <<>>           :: iodata() | undefined % = 2, optional
        }).
-endif.

-endif.
