%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.20.0

-ifndef(disconnect_reason_pb).
-define(disconnect_reason_pb, true).

-define(disconnect_reason_pb_gpb_version, "4.20.0").

-endif.
