%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.1

-ifndef(on_client_wakeup_pb).
-define(on_client_wakeup_pb, true).

-define(on_client_wakeup_pb_gpb_version, "4.19.1").

-ifndef('ONCLIENTWAKEUP_PB_H').
-define('ONCLIENTWAKEUP_PB_H', true).
-record('OnClientWakeUp',
        {client_id = <<>>       :: unicode:chardata() | undefined, % = 1, optional
         mountpoint = <<>>      :: unicode:chardata() | undefined % = 2, optional
        }).
-endif.

-endif.
