%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.1

-ifndef(on_delivery_complete_pb).
-define(on_delivery_complete_pb, true).

-define(on_delivery_complete_pb_gpb_version, "4.19.1").

-ifndef('ONDELIVERYCOMPLETE_PB_H').
-define('ONDELIVERYCOMPLETE_PB_H', true).
-record('OnDeliveryComplete',
        {username = <<>>        :: unicode:chardata() | undefined, % = 1, optional
         client_id = <<>>       :: unicode:chardata() | undefined, % = 2, optional
         mountpoint = <<>>      :: unicode:chardata() | undefined, % = 3, optional
         topic = <<>>           :: unicode:chardata() | undefined, % = 4, optional
         qos = 0                :: integer() | undefined, % = 5, optional, 32 bits
         is_retain = false      :: boolean() | 0 | 1 | undefined, % = 6, optional
         payload = <<>>         :: iodata() | undefined % = 7, optional
        }).
-endif.

-endif.
