%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.1

-ifndef(on_publish_pb).
-define(on_publish_pb, true).

-define(on_publish_pb_gpb_version, "4.19.1").

-ifndef('ONPUBLISH_PB_H').
-define('ONPUBLISH_PB_H', true).
-record('OnPublish',
        {username = <<>>        :: unicode:chardata() | undefined, % = 1, optional
         client_id = <<>>       :: unicode:chardata() | undefined, % = 2, optional
         mountpoint = <<>>      :: unicode:chardata() | undefined, % = 3, optional
         qos = 0                :: integer() | undefined, % = 4, optional, 32 bits
         topic = <<>>           :: unicode:chardata() | undefined, % = 5, optional
         payload = <<>>         :: iodata() | undefined, % = 6, optional
         retain = false         :: boolean() | 0 | 1 | undefined % = 7, optional
        }).
-endif.

-endif.
