%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.1

-ifndef(on_publish_pb).
-define(on_publish_pb, true).

-define(on_publish_pb_gpb_version, "4.19.1").

-ifndef('EVENTSSIDECAR.V1.ONPUBLISH_PB_H').
-define('EVENTSSIDECAR.V1.ONPUBLISH_PB_H', true).
-record('eventssidecar.v1.OnPublish',
        {timestamp = undefined  :: on_publish_pb:'google.protobuf.Timestamp'() | undefined, % = 1, optional
         username = <<>>        :: unicode:chardata() | undefined, % = 2, optional
         client_id = <<>>       :: unicode:chardata() | undefined, % = 3, optional
         mountpoint = <<>>      :: unicode:chardata() | undefined, % = 4, optional
         qos = 0                :: integer() | undefined, % = 5, optional, 32 bits
         topic = <<>>           :: unicode:chardata() | undefined, % = 6, optional
         payload = <<>>         :: iodata() | undefined, % = 7, optional
         retain = false         :: boolean() | 0 | 1 | undefined % = 8, optional
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.TIMESTAMP_PB_H').
-define('GOOGLE.PROTOBUF.TIMESTAMP_PB_H', true).
-record('google.protobuf.Timestamp',
        {seconds = 0            :: integer() | undefined, % = 1, optional, 64 bits
         nanos = 0              :: integer() | undefined % = 2, optional, 32 bits
        }).
-endif.

-endif.
