%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.1

-ifndef(on_register_pb).
-define(on_register_pb, true).

-define(on_register_pb_gpb_version, "4.19.1").

-ifndef('ONREGISTER_PB_H').
-define('ONREGISTER_PB_H', true).
-record('OnRegister',
        {peer_addr = <<>>       :: unicode:chardata() | undefined, % = 1, optional
         peer_port = 0          :: integer() | undefined, % = 2, optional, 32 bits
         username = <<>>        :: unicode:chardata() | undefined, % = 3, optional
         mountpoint = <<>>      :: unicode:chardata() | undefined, % = 4, optional
         client_id = <<>>       :: unicode:chardata() | undefined % = 5, optional
        }).
-endif.

-endif.
