%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.1

-ifndef(on_subscribe_pb).
-define(on_subscribe_pb, true).

-define(on_subscribe_pb_gpb_version, "4.19.1").

-ifndef('ONSUBSCRIBE_PB_H').
-define('ONSUBSCRIBE_PB_H', true).
-record('OnSubscribe',
        {client_id = <<>>       :: unicode:chardata() | undefined, % = 1, optional
         mountpoint = <<>>      :: unicode:chardata() | undefined, % = 2, optional
         username = <<>>        :: unicode:chardata() | undefined, % = 3, optional
         topics = []            :: [on_subscribe_pb:'TopicInfo'()] | undefined % = 4, repeated
        }).
-endif.

-ifndef('TOPICINFO_PB_H').
-define('TOPICINFO_PB_H', true).
-record('TopicInfo',
        {topic = <<>>           :: unicode:chardata() | undefined, % = 1, optional
         qos = 0                :: integer() | undefined % = 2, optional, 32 bits
        }).
-endif.

-endif.
