%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.1

-ifndef(on_unsubscribe_pb).
-define(on_unsubscribe_pb, true).

-define(on_unsubscribe_pb_gpb_version, "4.19.1").

-ifndef('ONUNSUBSCRIBE_PB_H').
-define('ONUNSUBSCRIBE_PB_H', true).
-record('OnUnsubscribe',
        {username = <<>>        :: unicode:chardata() | undefined, % = 1, optional
         client_id = <<>>       :: unicode:chardata() | undefined, % = 2, optional
         mountpoint = <<>>      :: unicode:chardata() | undefined, % = 3, optional
         topics = []            :: [unicode:chardata()] | undefined % = 4, repeated
        }).
-endif.

-endif.
