version: "3.9"
services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        environment:
          POSTGRES_USER: vmq_test_user
          POSTGRES_PASSWORD: vmq_test_password
          POSTGRES_DB: vmq_test_database
      mysql:
        image: mysql:5.7.33
        ports:
          - 3306:3306
        environment:
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
          MYSQL_USER: vmq_test_user
          MYSQL_PASSWORD: vmq_test_password
          MYSQL_DATABASE: vmq_test_database
      memcached:
        image: memcached
        ports:
          - 11211:11211
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: vmq_test_user
          MONGO_INITDB_ROOT_PASSWORD: vmq_test_password
      redis:
        image: redis
        ports:
          - 6379:6379
