-module(vmq_remap_subscriber_lua_SUITE).

-compile(export_all).
-compile(nowarn_export_all).

%% ===================================================================
%% common_test callbacks
%% ===================================================================
init_per_suite(_Config) ->
    cover:start(),
    [{ct_hooks, vmq_cth} |_Config].

end_per_suite(_Config) ->
    _Config.

init_per_testcase(_Case, Config) ->
    vmq_test_utils:setup(),
    Config.

end_per_testcase(_, Config) ->
    vmq_test_utils:teardown(),
    Config.

all() ->
    [
     new_subscriber_clean_session_true_test,
     new_subscriber_clean_session_false_test,
     clean_session_true_stale_request_test,
     clean_session_false_stale_request_test,
     clean_session_true_same_node_test,
     clean_session_true_different_node_test,
     normal_topic_subscriptions_clean_session_true_test,
     shared_topic_subscriptions_clean_session_true_test,
     shared_topic_subscriptions_clean_session_false_different_node_test,
     normal_topic_subscriptions_clean_session_false_different_node_test,
     normal_topic_subscriptions_clean_session_false_same_node_test,
     clean_session_false_different_node_test,
     clean_session_false_same_node_test
    ].

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Actual Tests
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

new_subscriber_clean_session_true_test(_) ->
    MP = "",
    ClientId = "CID-123",
    NodeName = <<"Node-A">>,
    CS = true,

    {ok, [undefined, [NodeName, <<"1">>, []]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                  remap_subscriber,
                                                                                  0,
                                                                                  MP,
                                                                                  ClientId,
                                                                                  NodeName,
                                                                                  CS,
                                                                                  os:system_time(nanosecond)]),
    ok.

new_subscriber_clean_session_false_test(_) ->
    MP = "",
    ClientId = "CID-123",
    NodeName = <<"Node-A">>,
    CS = false,

    {ok, [undefined, [NodeName, undefined, []]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                    remap_subscriber,
                                                                                    0,
                                                                                    MP,
                                                                                    ClientId,
                                                                                    NodeName,
                                                                                    CS,
                                                                                    os:system_time(nanosecond)]),
    ok.

clean_session_true_stale_request_test(_) ->
    MP = "",
    NodeName = <<"Node-A">>,
    ClientId = "CID-1",
    CS = true,
    OldTS = os:system_time(nanosecond),

    {ok, [undefined, [NodeName, <<"1">>, []]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                  remap_subscriber,
                                                                                  0,
                                                                                  MP,
                                                                                  ClientId,
                                                                                  NodeName,
                                                                                  CS,
                                                                                  OldTS]),
    {error, <<"ERR stale_request">>} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                        remap_subscriber,
                                                                        0,
                                                                        MP,
                                                                        ClientId,
                                                                        NodeName,
                                                                        CS,
                                                                        OldTS - 10000]),
    ok.

clean_session_false_stale_request_test(_) ->
    MP = "",
    NodeName = <<"Node-A">>,
    ClientId = "CID-1",
    CS = false,
    OldTS = os:system_time(nanosecond),

    {ok, [undefined, [NodeName, undefined, []]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                    remap_subscriber,
                                                                                    0,
                                                                                    MP,
                                                                                    ClientId,
                                                                                    NodeName,
                                                                                    CS,
                                                                                    OldTS]),
    {error, <<"ERR stale_request">>} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                        remap_subscriber,
                                                                        0,
                                                                        MP,
                                                                        ClientId,
                                                                        NodeName,
                                                                        CS,
                                                                        OldTS - 10000]),
    ok.

clean_session_true_same_node_test(_) ->
    MP = "",
    NodeName = <<"Node-A">>,
    ClientId = "CID-1",
    CS = true,

    {ok, [undefined, [NodeName, <<"1">>, []]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                  remap_subscriber,
                                                                                  0,
                                                                                  MP,
                                                                                  ClientId,
                                                                                  NodeName,
                                                                                  CS,
                                                                                  os:system_time(nanosecond)]),
    {ok, [<<"1">>, [NodeName, <<"1">>, []]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                remap_subscriber,
                                                                                0,
                                                                                MP,
                                                                                ClientId,
                                                                                NodeName,
                                                                                CS,
                                                                                os:system_time(nanosecond)]),
    ok.

clean_session_true_different_node_test(_) ->
    MP = "",
    NodeName1 = <<"Node-A">>,
    NodeName2 = <<"Node-B">>,
    ClientId = "CID-1",
    CS = true,

    {ok, [undefined, [NodeName1, <<"1">>, []]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                   remap_subscriber,
                                                                                   0,
                                                                                   MP,
                                                                                   ClientId,
                                                                                   NodeName1,
                                                                                   CS,
                                                                                   os:system_time(nanosecond)]),
    {ok,
     [<<"1">>, [NodeName2, <<"1">>, []], NodeName1]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                        remap_subscriber,
                                                                                        0,
                                                                                        MP,
                                                                                        ClientId,
                                                                                        NodeName2,
                                                                                        CS,
                                                                                        os:system_time(nanosecond)]),
    ok.

normal_topic_subscriptions_clean_session_true_test(_) ->
    MP = "",
    NodeName = <<"Node-A">>,
    ClientId = <<"CID-1">>,
    CS = true,
    Topic = <<"topic/abc">>,
    QoS = <<"1">>,

    {ok, [undefined, [NodeName, <<"1">>, []]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                  remap_subscriber,
                                                                                  0,
                                                                                  MP,
                                                                                  ClientId,
                                                                                  NodeName,
                                                                                  CS,
                                                                                  os:system_time(nanosecond)]),
    {ok, [NodeName, <<"1">>, []]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                     subscribe,
                                                                     0,
                                                                     MP,
                                                                     ClientId,
                                                                     NodeName,
                                                                     os:system_time(nanosecond),
                                                                     1,
                                                                     Topic,
                                                                     QoS]),
    {ok, [[NodeName, ClientId, QoS]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                         fetch_matched_topic_subscribers,
                                                                         0,
                                                                         MP,
                                                                         1,
                                                                         Topic]),
    {ok, [<<"1">>, [NodeName, <<"1">>, []]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                remap_subscriber,
                                                                                0,
                                                                                MP,
                                                                                ClientId,
                                                                                NodeName,
                                                                                CS,
                                                                                os:system_time(nanosecond)]),
    {ok, []} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                fetch_matched_topic_subscribers,
                                                0,
                                                MP,
                                                1,
                                                Topic]),
    ok.

shared_topic_subscriptions_clean_session_true_test(_) ->
    MP = "",
    NodeName = <<"Node-A">>,
    ClientId = <<"CID-1">>,
    CS = true,
    Topic = <<"topic/abc">>,
    Group = <<"group1">>,
    QoS = <<"1">>,

    {ok, [undefined, [NodeName, <<"1">>, []]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                  remap_subscriber,
                                                                                  0,
                                                                                  MP,
                                                                                  ClientId,
                                                                                  NodeName,
                                                                                  CS,
                                                                                  os:system_time(nanosecond)]),
    {ok, [NodeName, <<"1">>, []]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                     subscribe,
                                                                     0,
                                                                     MP,
                                                                     ClientId,
                                                                     NodeName,
                                                                     os:system_time(nanosecond),
                                                                     1,
                                                                     <<"$share/", Group/binary, "/", Topic/binary>>,
                                                                     QoS]),
    {ok, [[NodeName, Group, ClientId, QoS]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                fetch_matched_topic_subscribers,
                                                                                0,
                                                                                MP,
                                                                                1,
                                                                                Topic]),
    {ok, [<<"1">>, [NodeName, <<"1">>, []]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                remap_subscriber,
                                                                                0,
                                                                                MP,
                                                                                ClientId,
                                                                                NodeName,
                                                                                CS,
                                                                                os:system_time(nanosecond)]),
    {ok, []} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                fetch_matched_topic_subscribers,
                                                0,
                                                MP,
                                                1,
                                                Topic]),
    ok.

clean_session_false_same_node_test(_) ->
    MP = "",
    NodeName = <<"Node-A">>,
    ClientId = "CID-1",
    CS = false,

    {ok, [undefined, [NodeName, undefined, []]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                    remap_subscriber,
                                                                                    0,
                                                                                    MP,
                                                                                    ClientId,
                                                                                    NodeName,
                                                                                    CS,
                                                                                    os:system_time(nanosecond)]),
    {ok, [<<"1">>, [NodeName, undefined, []]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                  remap_subscriber,
                                                                                  0,
                                                                                  MP,
                                                                                  ClientId,
                                                                                  NodeName,
                                                                                  CS,
                                                                                  os:system_time(nanosecond)]),
    ok.

clean_session_false_different_node_test(_) ->
    MP = "",
    NodeName1 = <<"Node-A">>,
    NodeName2 = <<"Node-B">>,
    ClientId = "CID-1",
    CS = false,

    {ok, [undefined, [NodeName1, undefined, []]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                     remap_subscriber,
                                                                                     0,
                                                                                     MP,
                                                                                     ClientId,
                                                                                     NodeName1,
                                                                                     CS,
                                                                                     os:system_time(nanosecond)]),
    {ok,
     [<<"1">>, [NodeName2, undefined, []], NodeName1]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                          remap_subscriber,
                                                                                          0,
                                                                                          MP,
                                                                                          ClientId,
                                                                                          NodeName2,
                                                                                          CS,
                                                                                          os:system_time(nanosecond)]),
    ok.

normal_topic_subscriptions_clean_session_false_same_node_test(_) ->
    MP = "",
    NodeName = <<"Node-A">>,
    ClientId = <<"CID-1">>,
    CS = false,
    Topic = <<"topic/abc">>,
    QoS = <<"1">>,

    {ok, [undefined, [NodeName, undefined, []]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                    remap_subscriber,
                                                                                    0,
                                                                                    MP,
                                                                                    ClientId,
                                                                                    NodeName,
                                                                                    CS,
                                                                                    os:system_time(nanosecond)]),
    {ok, [NodeName, undefined, []]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                       subscribe,
                                                                       0,
                                                                       MP,
                                                                       ClientId,
                                                                       NodeName,
                                                                       os:system_time(nanosecond),
                                                                       1,
                                                                       Topic,
                                                                       QoS]),
    {ok, [[NodeName, ClientId, QoS]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                         fetch_matched_topic_subscribers,
                                                                         0,
                                                                         MP,
                                                                         1,
                                                                         Topic]),
    {ok,
     [<<"1">>, [NodeName, undefined, [[Topic, QoS]]]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                          remap_subscriber,
                                                                                          0,
                                                                                          MP,
                                                                                          ClientId,
                                                                                          NodeName,
                                                                                          CS,
                                                                                          os:system_time(nanosecond)]),
    {ok, [[NodeName, ClientId, QoS]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                         fetch_matched_topic_subscribers,
                                                                         0,
                                                                         MP,
                                                                         1,
                                                                         Topic]),
    ok.

normal_topic_subscriptions_clean_session_false_different_node_test(_) ->
    MP = "",
    NodeName1 = <<"Node-A">>,
    NodeName2 = <<"Node-B">>,
    ClientId = <<"CID-1">>,
    CS = false,
    Topic = <<"topic/abc">>,
    QoS = <<"1">>,

    {ok, [undefined, [NodeName1, undefined, []]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                     remap_subscriber,
                                                                                     0,
                                                                                     MP,
                                                                                     ClientId,
                                                                                     NodeName1,
                                                                                     CS,
                                                                                     os:system_time(nanosecond)]),
    {ok, [NodeName1, undefined, []]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                        subscribe,
                                                                        0,
                                                                        MP,
                                                                        ClientId,
                                                                        NodeName1,
                                                                        os:system_time(nanosecond),
                                                                        1,
                                                                        Topic,
                                                                        QoS]),
    {ok, [[NodeName1, ClientId, QoS]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                          fetch_matched_topic_subscribers,
                                                                          0,
                                                                          MP,
                                                                          1,
                                                                          Topic]),
    {ok,
     [<<"1">>,
      [NodeName2, undefined, [[Topic, QoS]]],
      NodeName1]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                     remap_subscriber,
                                                     0,
                                                     MP,
                                                     ClientId,
                                                     NodeName2,
                                                     CS,
                                                     os:system_time(nanosecond)]),
    {ok, [[NodeName2, ClientId, QoS]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                          fetch_matched_topic_subscribers,
                                                                          0,
                                                                          MP,
                                                                          1,
                                                                          Topic]),
    ok.

shared_topic_subscriptions_clean_session_false_different_node_test(_) ->
    MP = "",
    NodeName1 = <<"Node-A">>,
    NodeName2 = <<"Node-B">>,
    ClientId = <<"CID-1">>,
    CS = false,
    Topic = <<"topic/abc">>,
    Group = <<"group1">>,
    SharedTopic = <<"$share/", Group/binary, "/", Topic/binary>>,
    QoS = <<"1">>,

    {ok, [undefined, [NodeName1, undefined, []]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                     remap_subscriber,
                                                                                     0,
                                                                                     MP,
                                                                                     ClientId,
                                                                                     NodeName1,
                                                                                     CS,
                                                                                     os:system_time(nanosecond)]),
    {ok, [NodeName1, undefined, []]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                        subscribe,
                                                                        0,
                                                                        MP,
                                                                        ClientId,
                                                                        NodeName1,
                                                                        os:system_time(nanosecond),
                                                                        1,
                                                                        SharedTopic,
                                                                        QoS]),
    {ok, [[NodeName1, Group, ClientId, QoS]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                 fetch_matched_topic_subscribers,
                                                                                 0,
                                                                                 MP,
                                                                                 1,
                                                                                 Topic]),
    {ok,
     [<<"1">>,
      [NodeName2, undefined, [[SharedTopic, QoS]]],
      NodeName1]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                     remap_subscriber,
                                                     0,
                                                     MP,
                                                     ClientId,
                                                     NodeName2,
                                                     CS,
                                                     os:system_time(nanosecond)]),
    {ok, [[NodeName2, Group, ClientId, QoS]]} = eredis:q(whereis(vmq_redis_client), ["FCALL",
                                                                                 fetch_matched_topic_subscribers,
                                                                                 0,
                                                                                 MP,
                                                                                 1,
                                                                                 Topic]),
    ok.