name: 🔧 New improvement or feature request
description: Create a report to help us improve
title: "<title>"
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue, please make sure that there isn't already an open (or closed/resolved) issue
         reporting the same problem. Please always open a new issue rather than posting to a closed one -
         but please reference the possibly related old issue.

        Please do not insert images of text, but add the text instead.
  - type: textarea
    id: issue
    attributes:
      label: Describe your issue or feature request
      description: |
        A clear and concise description of what the problem is.
        Ex. I find the `vmq-admin` commands hard to use because [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you would like to happen.
        Links to other projects or any previous art.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **VerneMQ Version:**
          - **OS:** Ubuntu 20.04
          - **Erlang/OTP version (if building from source)**: 25.0
          - **Cluster size/standalone**: 3 nodes
      value: |
        - VerneMQ Version:
        - OS:
        - Erlang/OTP version (if building from source):
        - Cluster size/standalone:
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Add any other context, code samples or screenshots about the issue report here.
      description: Additional context
      render: markdown
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/vernemq/vernemq/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow the VerneMQ's Code of Conduct
          required: true
