%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.20.0
%% Version source: file
-module(on_client_offline_pb).

-export([encode_msg/1, encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/2, merge_msgs/3, merge_msgs/4]).
-export([verify_msg/1, verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([
    'enum_symbol_by_value_eventssidecar.v1.Reason'/1,
    'enum_value_by_symbol_eventssidecar.v1.Reason'/1
]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([fqbin_to_service_name/1]).
-export([service_name_to_fqbin/1]).
-export([fqbins_to_service_and_rpc_name/2]).
-export([service_and_rpc_name_to_fqbins/2]).
-export([fqbin_to_msg_name/1]).
-export([msg_name_to_fqbin/1]).
-export([fqbin_to_enum_name/1]).
-export([enum_name_to_fqbin/1]).
-export([get_package_name/0]).
-export([uses_packages/0]).
-export([source_basename/0]).
-export([get_all_source_basenames/0]).
-export([get_all_proto_names/0]).
-export([get_msg_containment/1]).
-export([get_pkg_containment/1]).
-export([get_service_containment/1]).
-export([get_rpc_containment/1]).
-export([get_enum_containment/1]).
-export([get_proto_by_msg_name_as_fqbin/1]).
-export([get_proto_by_service_name_as_fqbin/1]).
-export([get_proto_by_enum_name_as_fqbin/1]).
-export([get_protos_by_pkg_name_as_fqbin/1]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).
-export([gpb_version_source/0]).

-include("on_client_offline_pb.hrl").
-include("gpb.hrl").

%% enumerated types
-type 'eventssidecar.v1.Reason'() ::
    'REASON_UNSPECIFIED'
    | 'REASON_NOT_AUTHORIZED'
    | 'REASON_NORMAL_DISCONNECT'
    | 'REASON_SESSION_TAKEN_OVER'
    | 'REASON_ADMINISTRATIVE_ACTION'
    | 'REASON_DISCONNECT_KEEP_ALIVE'
    | 'REASON_DISCONNECT_MIGRATION'
    | 'REASON_BAD_AUTHENTICATION_METHOD'
    | 'REASON_REMOTE_SESSION_TAKEN_OVER'
    | 'REASON_MQTT_CLIENT_DISCONNECT'
    | 'REASON_RECEIVE_MAX_EXCEEDED'
    | 'REASON_PROTOCOL_ERROR'
    | 'REASON_PUBLISH_AUTH_ERROR'
    | 'REASON_INVALID_PUBREC_ERROR'
    | 'REASON_INVALID_PUBCOMP_ERROR'
    | 'REASON_UNEXPECTED_FRAME_TYPE'
    | 'REASON_EXIT_SIGNAL_RECEIVED'
    | 'REASON_TCP_CLOSED'.
-export_type(['eventssidecar.v1.Reason'/0]).

%% message types
-type 'eventssidecar.v1.OnClientOffline'() :: #'eventssidecar.v1.OnClientOffline'{}.

-type 'google.protobuf.Timestamp'() :: #'google.protobuf.Timestamp'{}.

-export_type(['eventssidecar.v1.OnClientOffline'/0, 'google.protobuf.Timestamp'/0]).
-type '$msg_name'() :: 'eventssidecar.v1.OnClientOffline' | 'google.protobuf.Timestamp'.
-type '$msg'() :: 'eventssidecar.v1.OnClientOffline'() | 'google.protobuf.Timestamp'().
-export_type(['$msg_name'/0, '$msg'/0]).

-spec encode_msg('$msg'()) -> binary().
encode_msg(Msg) when tuple_size(Msg) >= 1 -> encode_msg(Msg, element(1, Msg), []).

-spec encode_msg('$msg'(), '$msg_name'() | list()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) -> encode_msg(Msg, MsgName, []);
encode_msg(Msg, Opts) when tuple_size(Msg) >= 1, is_list(Opts) ->
    encode_msg(Msg, element(1, Msg), Opts).

-spec encode_msg('$msg'(), '$msg_name'(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
        true -> verify_msg(Msg, MsgName, Opts);
        false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'eventssidecar.v1.OnClientOffline' ->
            'encode_msg_eventssidecar.v1.OnClientOffline'(id(Msg, TrUserData), TrUserData);
        'google.protobuf.Timestamp' ->
            'encode_msg_google.protobuf.Timestamp'(id(Msg, TrUserData), TrUserData)
    end.

'encode_msg_eventssidecar.v1.OnClientOffline'(Msg, TrUserData) ->
    'encode_msg_eventssidecar.v1.OnClientOffline'(Msg, <<>>, TrUserData).

'encode_msg_eventssidecar.v1.OnClientOffline'(
    #'eventssidecar.v1.OnClientOffline'{
        timestamp = F1, client_id = F2, mountpoint = F3, reason = F4
    },
    Bin,
    TrUserData
) ->
    B1 =
        if
            F1 == undefined ->
                Bin;
            true ->
                begin
                    TrF1 = id(F1, TrUserData),
                    if
                        TrF1 =:= undefined ->
                            Bin;
                        true ->
                            'e_mfield_eventssidecar.v1.OnClientOffline_timestamp'(
                                TrF1, <<Bin/binary, 10>>, TrUserData
                            )
                    end
                end
        end,
    B2 =
        if
            F2 == undefined ->
                B1;
            true ->
                begin
                    TrF2 = id(F2, TrUserData),
                    case is_empty_string(TrF2) of
                        true -> B1;
                        false -> e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
                    end
                end
        end,
    B3 =
        if
            F3 == undefined ->
                B2;
            true ->
                begin
                    TrF3 = id(F3, TrUserData),
                    case is_empty_string(TrF3) of
                        true -> B2;
                        false -> e_type_string(TrF3, <<B2/binary, 26>>, TrUserData)
                    end
                end
        end,
    if
        F4 == undefined ->
            B3;
        true ->
            begin
                TrF4 = id(F4, TrUserData),
                if
                    TrF4 =:= 'REASON_UNSPECIFIED'; TrF4 =:= 0 -> B3;
                    true -> 'e_enum_eventssidecar.v1.Reason'(TrF4, <<B3/binary, 32>>, TrUserData)
                end
            end
    end.

'encode_msg_google.protobuf.Timestamp'(Msg, TrUserData) ->
    'encode_msg_google.protobuf.Timestamp'(Msg, <<>>, TrUserData).

'encode_msg_google.protobuf.Timestamp'(
    #'google.protobuf.Timestamp'{seconds = F1, nanos = F2}, Bin, TrUserData
) ->
    B1 =
        if
            F1 == undefined ->
                Bin;
            true ->
                begin
                    TrF1 = id(F1, TrUserData),
                    if
                        TrF1 =:= 0 -> Bin;
                        true -> e_type_int64(TrF1, <<Bin/binary, 8>>, TrUserData)
                    end
                end
        end,
    if
        F2 == undefined ->
            B1;
        true ->
            begin
                TrF2 = id(F2, TrUserData),
                if
                    TrF2 =:= 0 -> B1;
                    true -> e_type_int32(TrF2, <<B1/binary, 16>>, TrUserData)
                end
            end
    end.

'e_mfield_eventssidecar.v1.OnClientOffline_timestamp'(Msg, Bin, TrUserData) ->
    SubBin = 'encode_msg_google.protobuf.Timestamp'(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

'e_enum_eventssidecar.v1.Reason'('REASON_UNSPECIFIED', Bin, _TrUserData) ->
    <<Bin/binary, 0>>;
'e_enum_eventssidecar.v1.Reason'('REASON_NOT_AUTHORIZED', Bin, _TrUserData) ->
    <<Bin/binary, 1>>;
'e_enum_eventssidecar.v1.Reason'('REASON_NORMAL_DISCONNECT', Bin, _TrUserData) ->
    <<Bin/binary, 2>>;
'e_enum_eventssidecar.v1.Reason'('REASON_SESSION_TAKEN_OVER', Bin, _TrUserData) ->
    <<Bin/binary, 3>>;
'e_enum_eventssidecar.v1.Reason'('REASON_ADMINISTRATIVE_ACTION', Bin, _TrUserData) ->
    <<Bin/binary, 4>>;
'e_enum_eventssidecar.v1.Reason'('REASON_DISCONNECT_KEEP_ALIVE', Bin, _TrUserData) ->
    <<Bin/binary, 5>>;
'e_enum_eventssidecar.v1.Reason'('REASON_DISCONNECT_MIGRATION', Bin, _TrUserData) ->
    <<Bin/binary, 6>>;
'e_enum_eventssidecar.v1.Reason'('REASON_BAD_AUTHENTICATION_METHOD', Bin, _TrUserData) ->
    <<Bin/binary, 7>>;
'e_enum_eventssidecar.v1.Reason'('REASON_REMOTE_SESSION_TAKEN_OVER', Bin, _TrUserData) ->
    <<Bin/binary, 8>>;
'e_enum_eventssidecar.v1.Reason'('REASON_MQTT_CLIENT_DISCONNECT', Bin, _TrUserData) ->
    <<Bin/binary, 9>>;
'e_enum_eventssidecar.v1.Reason'('REASON_RECEIVE_MAX_EXCEEDED', Bin, _TrUserData) ->
    <<Bin/binary, 10>>;
'e_enum_eventssidecar.v1.Reason'('REASON_PROTOCOL_ERROR', Bin, _TrUserData) ->
    <<Bin/binary, 11>>;
'e_enum_eventssidecar.v1.Reason'('REASON_PUBLISH_AUTH_ERROR', Bin, _TrUserData) ->
    <<Bin/binary, 12>>;
'e_enum_eventssidecar.v1.Reason'('REASON_INVALID_PUBREC_ERROR', Bin, _TrUserData) ->
    <<Bin/binary, 13>>;
'e_enum_eventssidecar.v1.Reason'('REASON_INVALID_PUBCOMP_ERROR', Bin, _TrUserData) ->
    <<Bin/binary, 14>>;
'e_enum_eventssidecar.v1.Reason'('REASON_UNEXPECTED_FRAME_TYPE', Bin, _TrUserData) ->
    <<Bin/binary, 15>>;
'e_enum_eventssidecar.v1.Reason'('REASON_EXIT_SIGNAL_RECEIVED', Bin, _TrUserData) ->
    <<Bin/binary, 16>>;
'e_enum_eventssidecar.v1.Reason'('REASON_TCP_CLOSED', Bin, _TrUserData) ->
    <<Bin/binary, 17>>;
'e_enum_eventssidecar.v1.Reason'(V, Bin, _TrUserData) ->
    e_varint(V, Bin).

-compile({nowarn_unused_function, e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 -> e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) -> e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function, e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function, e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function, e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) -> <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function, e_type_string/3}).
e_type_string(S, Bin, _TrUserData) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function, e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData) when is_binary(Bytes) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData) when is_list(Bytes) ->
    BytesBin = iolist_to_binary(Bytes),
    Bin2 = e_varint(byte_size(BytesBin), Bin),
    <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function, e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function, e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function, e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function, e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function, e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) -> <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) -> <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) -> <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) -> <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function, e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) -> <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) -> <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) -> <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) -> <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function, e_unknown_elems/2}).
e_unknown_elems([Elem | Rest], Bin) ->
    BinR =
        case Elem of
            {varint, FNum, N} ->
                BinF = e_varint(FNum bsl 3, Bin),
                e_varint(N, BinF);
            {length_delimited, FNum, Data} ->
                BinF = e_varint(FNum bsl 3 bor 2, Bin),
                BinL = e_varint(byte_size(Data), BinF),
                <<BinL/binary, Data/binary>>;
            {group, FNum, GroupFields} ->
                Bin1 = e_varint(FNum bsl 3 bor 3, Bin),
                Bin2 = e_unknown_elems(GroupFields, Bin1),
                e_varint(FNum bsl 3 bor 4, Bin2);
            {fixed32, FNum, V} ->
                BinF = e_varint(FNum bsl 3 bor 5, Bin),
                <<BinF/binary, V:32/little>>;
            {fixed64, FNum, V} ->
                BinF = e_varint(FNum bsl 3 bor 1, Bin),
                <<BinF/binary, V:64/little>>
        end,
    e_unknown_elems(Rest, BinR);
e_unknown_elems([], Bin) ->
    Bin.

-compile({nowarn_unused_function, e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function, e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).

is_empty_string("") -> true;
is_empty_string(<<>>) -> true;
is_empty_string(L) when is_list(L) -> not string_has_chars(L);
is_empty_string(B) when is_binary(B) -> false.

string_has_chars([C | _]) when is_integer(C) -> true;
string_has_chars([H | T]) ->
    case string_has_chars(H) of
        true -> true;
        false -> string_has_chars(T)
    end;
string_has_chars(B) when is_binary(B), byte_size(B) =/= 0 -> true;
string_has_chars(C) when is_integer(C) -> true;
string_has_chars(<<>>) ->
    false;
string_has_chars([]) ->
    false.

decode_msg(Bin, MsgName) when is_binary(Bin) -> decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try
        decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error, _} = Reason:StackTrace ->
            erlang:raise(error, Reason, StackTrace);
        Class:Reason:StackTrace ->
            error({gpb_error, {decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try
        decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error, _} = Reason ->
            erlang:raise(
                error,
                Reason,
                erlang:get_stacktrace()
            );
        Class:Reason ->
            StackTrace = erlang:get_stacktrace(),
            error({gpb_error, {decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit('eventssidecar.v1.OnClientOffline', Bin, TrUserData) ->
    id('decode_msg_eventssidecar.v1.OnClientOffline'(Bin, TrUserData), TrUserData);
decode_msg_2_doit('google.protobuf.Timestamp', Bin, TrUserData) ->
    id('decode_msg_google.protobuf.Timestamp'(Bin, TrUserData), TrUserData).

'decode_msg_eventssidecar.v1.OnClientOffline'(Bin, TrUserData) ->
    'dfp_read_field_def_eventssidecar.v1.OnClientOffline'(
        Bin,
        0,
        0,
        0,
        id(undefined, TrUserData),
        id(<<>>, TrUserData),
        id(<<>>, TrUserData),
        id('REASON_UNSPECIFIED', TrUserData),
        TrUserData
    ).

'dfp_read_field_def_eventssidecar.v1.OnClientOffline'(
    <<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData
) ->
    'd_field_eventssidecar.v1.OnClientOffline_timestamp'(
        Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData
    );
'dfp_read_field_def_eventssidecar.v1.OnClientOffline'(
    <<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData
) ->
    'd_field_eventssidecar.v1.OnClientOffline_client_id'(
        Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData
    );
'dfp_read_field_def_eventssidecar.v1.OnClientOffline'(
    <<26, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData
) ->
    'd_field_eventssidecar.v1.OnClientOffline_mountpoint'(
        Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData
    );
'dfp_read_field_def_eventssidecar.v1.OnClientOffline'(
    <<32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData
) ->
    'd_field_eventssidecar.v1.OnClientOffline_reason'(
        Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData
    );
'dfp_read_field_def_eventssidecar.v1.OnClientOffline'(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, _) ->
    #'eventssidecar.v1.OnClientOffline'{
        timestamp = F@_1, client_id = F@_2, mountpoint = F@_3, reason = F@_4
    };
'dfp_read_field_def_eventssidecar.v1.OnClientOffline'(
    Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData
) ->
    'dg_read_field_def_eventssidecar.v1.OnClientOffline'(
        Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData
    ).

'dg_read_field_def_eventssidecar.v1.OnClientOffline'(
    <<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData
) when N < 32 - 7 ->
    'dg_read_field_def_eventssidecar.v1.OnClientOffline'(
        Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData
    );
'dg_read_field_def_eventssidecar.v1.OnClientOffline'(
    <<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, F@_4, TrUserData
) ->
    Key = X bsl N + Acc,
    case Key of
        10 ->
            'd_field_eventssidecar.v1.OnClientOffline_timestamp'(
                Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData
            );
        18 ->
            'd_field_eventssidecar.v1.OnClientOffline_client_id'(
                Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData
            );
        26 ->
            'd_field_eventssidecar.v1.OnClientOffline_mountpoint'(
                Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData
            );
        32 ->
            'd_field_eventssidecar.v1.OnClientOffline_reason'(
                Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData
            );
        _ ->
            case Key band 7 of
                0 ->
                    'skip_varint_eventssidecar.v1.OnClientOffline'(
                        Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData
                    );
                1 ->
                    'skip_64_eventssidecar.v1.OnClientOffline'(
                        Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData
                    );
                2 ->
                    'skip_length_delimited_eventssidecar.v1.OnClientOffline'(
                        Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData
                    );
                3 ->
                    'skip_group_eventssidecar.v1.OnClientOffline'(
                        Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData
                    );
                5 ->
                    'skip_32_eventssidecar.v1.OnClientOffline'(
                        Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData
                    )
            end
    end;
'dg_read_field_def_eventssidecar.v1.OnClientOffline'(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, _) ->
    #'eventssidecar.v1.OnClientOffline'{
        timestamp = F@_1, client_id = F@_2, mountpoint = F@_3, reason = F@_4
    }.

'd_field_eventssidecar.v1.OnClientOffline_timestamp'(
    <<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData
) when N < 57 ->
    'd_field_eventssidecar.v1.OnClientOffline_timestamp'(
        Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData
    );
'd_field_eventssidecar.v1.OnClientOffline_timestamp'(
    <<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, F@_2, F@_3, F@_4, TrUserData
) ->
    {NewFValue, RestF} = begin
        Len = X bsl N + Acc,
        <<Bs:Len/binary, Rest2/binary>> = Rest,
        {id('decode_msg_google.protobuf.Timestamp'(Bs, TrUserData), TrUserData), Rest2}
    end,
    'dfp_read_field_def_eventssidecar.v1.OnClientOffline'(
        RestF,
        0,
        0,
        F,
        if
            Prev == undefined -> NewFValue;
            true -> 'merge_msg_google.protobuf.Timestamp'(Prev, NewFValue, TrUserData)
        end,
        F@_2,
        F@_3,
        F@_4,
        TrUserData
    ).

'd_field_eventssidecar.v1.OnClientOffline_client_id'(
    <<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData
) when N < 57 ->
    'd_field_eventssidecar.v1.OnClientOffline_client_id'(
        Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData
    );
'd_field_eventssidecar.v1.OnClientOffline_client_id'(
    <<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, F@_4, TrUserData
) ->
    {NewFValue, RestF} = begin
        Len = X bsl N + Acc,
        <<Bytes:Len/binary, Rest2/binary>> = Rest,
        Bytes2 = binary:copy(Bytes),
        {id(Bytes2, TrUserData), Rest2}
    end,
    'dfp_read_field_def_eventssidecar.v1.OnClientOffline'(
        RestF, 0, 0, F, F@_1, NewFValue, F@_3, F@_4, TrUserData
    ).

'd_field_eventssidecar.v1.OnClientOffline_mountpoint'(
    <<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData
) when N < 57 ->
    'd_field_eventssidecar.v1.OnClientOffline_mountpoint'(
        Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData
    );
'd_field_eventssidecar.v1.OnClientOffline_mountpoint'(
    <<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, F@_4, TrUserData
) ->
    {NewFValue, RestF} = begin
        Len = X bsl N + Acc,
        <<Bytes:Len/binary, Rest2/binary>> = Rest,
        Bytes2 = binary:copy(Bytes),
        {id(Bytes2, TrUserData), Rest2}
    end,
    'dfp_read_field_def_eventssidecar.v1.OnClientOffline'(
        RestF, 0, 0, F, F@_1, F@_2, NewFValue, F@_4, TrUserData
    ).

'd_field_eventssidecar.v1.OnClientOffline_reason'(
    <<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData
) when N < 57 ->
    'd_field_eventssidecar.v1.OnClientOffline_reason'(
        Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData
    );
'd_field_eventssidecar.v1.OnClientOffline_reason'(
    <<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, _, TrUserData
) ->
    {NewFValue, RestF} = {
        id(
            'd_enum_eventssidecar.v1.Reason'(begin
                <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>,
                id(Res, TrUserData)
            end),
            TrUserData
        ),
        Rest
    },
    'dfp_read_field_def_eventssidecar.v1.OnClientOffline'(
        RestF, 0, 0, F, F@_1, F@_2, F@_3, NewFValue, TrUserData
    ).

'skip_varint_eventssidecar.v1.OnClientOffline'(
    <<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData
) ->
    'skip_varint_eventssidecar.v1.OnClientOffline'(
        Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData
    );
'skip_varint_eventssidecar.v1.OnClientOffline'(
    <<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData
) ->
    'dfp_read_field_def_eventssidecar.v1.OnClientOffline'(
        Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData
    ).

'skip_length_delimited_eventssidecar.v1.OnClientOffline'(
    <<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData
) when N < 57 ->
    'skip_length_delimited_eventssidecar.v1.OnClientOffline'(
        Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData
    );
'skip_length_delimited_eventssidecar.v1.OnClientOffline'(
    <<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData
) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    'dfp_read_field_def_eventssidecar.v1.OnClientOffline'(
        Rest2, 0, 0, F, F@_1, F@_2, F@_3, F@_4, TrUserData
    ).

'skip_group_eventssidecar.v1.OnClientOffline'(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    'dfp_read_field_def_eventssidecar.v1.OnClientOffline'(
        Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData
    ).

'skip_32_eventssidecar.v1.OnClientOffline'(
    <<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData
) ->
    'dfp_read_field_def_eventssidecar.v1.OnClientOffline'(
        Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData
    ).

'skip_64_eventssidecar.v1.OnClientOffline'(
    <<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData
) ->
    'dfp_read_field_def_eventssidecar.v1.OnClientOffline'(
        Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData
    ).

'decode_msg_google.protobuf.Timestamp'(Bin, TrUserData) ->
    'dfp_read_field_def_google.protobuf.Timestamp'(
        Bin, 0, 0, 0, id(0, TrUserData), id(0, TrUserData), TrUserData
    ).

'dfp_read_field_def_google.protobuf.Timestamp'(
    <<8, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData
) ->
    'd_field_google.protobuf.Timestamp_seconds'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'dfp_read_field_def_google.protobuf.Timestamp'(
    <<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData
) ->
    'd_field_google.protobuf.Timestamp_nanos'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'dfp_read_field_def_google.protobuf.Timestamp'(<<>>, 0, 0, _, F@_1, F@_2, _) ->
    #'google.protobuf.Timestamp'{seconds = F@_1, nanos = F@_2};
'dfp_read_field_def_google.protobuf.Timestamp'(Other, Z1, Z2, F, F@_1, F@_2, TrUserData) ->
    'dg_read_field_def_google.protobuf.Timestamp'(Other, Z1, Z2, F, F@_1, F@_2, TrUserData).

'dg_read_field_def_google.protobuf.Timestamp'(
    <<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData
) when N < 32 - 7 ->
    'dg_read_field_def_google.protobuf.Timestamp'(
        Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData
    );
'dg_read_field_def_google.protobuf.Timestamp'(
    <<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, TrUserData
) ->
    Key = X bsl N + Acc,
    case Key of
        8 ->
            'd_field_google.protobuf.Timestamp_seconds'(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        16 ->
            'd_field_google.protobuf.Timestamp_nanos'(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        _ ->
            case Key band 7 of
                0 ->
                    'skip_varint_google.protobuf.Timestamp'(
                        Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData
                    );
                1 ->
                    'skip_64_google.protobuf.Timestamp'(
                        Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData
                    );
                2 ->
                    'skip_length_delimited_google.protobuf.Timestamp'(
                        Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData
                    );
                3 ->
                    'skip_group_google.protobuf.Timestamp'(
                        Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData
                    );
                5 ->
                    'skip_32_google.protobuf.Timestamp'(
                        Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData
                    )
            end
    end;
'dg_read_field_def_google.protobuf.Timestamp'(<<>>, 0, 0, _, F@_1, F@_2, _) ->
    #'google.protobuf.Timestamp'{seconds = F@_1, nanos = F@_2}.

'd_field_google.protobuf.Timestamp_seconds'(
    <<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData
) when N < 57 ->
    'd_field_google.protobuf.Timestamp_seconds'(
        Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData
    );
'd_field_google.protobuf.Timestamp_seconds'(
    <<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, TrUserData
) ->
    {NewFValue, RestF} = {
        begin
            <<Res:64/signed-native>> = <<(X bsl N + Acc):64/unsigned-native>>,
            id(Res, TrUserData)
        end,
        Rest
    },
    'dfp_read_field_def_google.protobuf.Timestamp'(RestF, 0, 0, F, NewFValue, F@_2, TrUserData).

'd_field_google.protobuf.Timestamp_nanos'(
    <<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData
) when N < 57 ->
    'd_field_google.protobuf.Timestamp_nanos'(
        Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData
    );
'd_field_google.protobuf.Timestamp_nanos'(
    <<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, TrUserData
) ->
    {NewFValue, RestF} = {
        begin
            <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>,
            id(Res, TrUserData)
        end,
        Rest
    },
    'dfp_read_field_def_google.protobuf.Timestamp'(RestF, 0, 0, F, F@_1, NewFValue, TrUserData).

'skip_varint_google.protobuf.Timestamp'(
    <<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData
) ->
    'skip_varint_google.protobuf.Timestamp'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'skip_varint_google.protobuf.Timestamp'(
    <<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData
) ->
    'dfp_read_field_def_google.protobuf.Timestamp'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

'skip_length_delimited_google.protobuf.Timestamp'(
    <<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData
) when N < 57 ->
    'skip_length_delimited_google.protobuf.Timestamp'(
        Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData
    );
'skip_length_delimited_google.protobuf.Timestamp'(
    <<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData
) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    'dfp_read_field_def_google.protobuf.Timestamp'(Rest2, 0, 0, F, F@_1, F@_2, TrUserData).

'skip_group_google.protobuf.Timestamp'(Bin, _, Z2, FNum, F@_1, F@_2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    'dfp_read_field_def_google.protobuf.Timestamp'(Rest, 0, Z2, FNum, F@_1, F@_2, TrUserData).

'skip_32_google.protobuf.Timestamp'(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) ->
    'dfp_read_field_def_google.protobuf.Timestamp'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

'skip_64_google.protobuf.Timestamp'(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) ->
    'dfp_read_field_def_google.protobuf.Timestamp'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

'd_enum_eventssidecar.v1.Reason'(0) -> 'REASON_UNSPECIFIED';
'd_enum_eventssidecar.v1.Reason'(1) -> 'REASON_NOT_AUTHORIZED';
'd_enum_eventssidecar.v1.Reason'(2) -> 'REASON_NORMAL_DISCONNECT';
'd_enum_eventssidecar.v1.Reason'(3) -> 'REASON_SESSION_TAKEN_OVER';
'd_enum_eventssidecar.v1.Reason'(4) -> 'REASON_ADMINISTRATIVE_ACTION';
'd_enum_eventssidecar.v1.Reason'(5) -> 'REASON_DISCONNECT_KEEP_ALIVE';
'd_enum_eventssidecar.v1.Reason'(6) -> 'REASON_DISCONNECT_MIGRATION';
'd_enum_eventssidecar.v1.Reason'(7) -> 'REASON_BAD_AUTHENTICATION_METHOD';
'd_enum_eventssidecar.v1.Reason'(8) -> 'REASON_REMOTE_SESSION_TAKEN_OVER';
'd_enum_eventssidecar.v1.Reason'(9) -> 'REASON_MQTT_CLIENT_DISCONNECT';
'd_enum_eventssidecar.v1.Reason'(10) -> 'REASON_RECEIVE_MAX_EXCEEDED';
'd_enum_eventssidecar.v1.Reason'(11) -> 'REASON_PROTOCOL_ERROR';
'd_enum_eventssidecar.v1.Reason'(12) -> 'REASON_PUBLISH_AUTH_ERROR';
'd_enum_eventssidecar.v1.Reason'(13) -> 'REASON_INVALID_PUBREC_ERROR';
'd_enum_eventssidecar.v1.Reason'(14) -> 'REASON_INVALID_PUBCOMP_ERROR';
'd_enum_eventssidecar.v1.Reason'(15) -> 'REASON_UNEXPECTED_FRAME_TYPE';
'd_enum_eventssidecar.v1.Reason'(16) -> 'REASON_EXIT_SIGNAL_RECEIVED';
'd_enum_eventssidecar.v1.Reason'(17) -> 'REASON_TCP_CLOSED';
'd_enum_eventssidecar.v1.Reason'(V) -> V.

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum) when
    N < (32 - 7)
->
    read_gr_b(Tl, N + 7, X bsl N + Acc, NumBytes, TagLen + 1, FieldNum);
read_gr_b(
    <<0:1, X:7, Tl/binary>>,
    N,
    Acc,
    NumBytes,
    TagLen,
    FieldNum
) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        % 4 = group_end
        {FieldNum, 4} ->
            {NumBytes, TagLen1};
        % 0 = varint
        {_, 0} ->
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        % 1 = bits64
        {_, 1} ->
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        % 2 = length_delimited
        {_, 2} ->
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        % 3 = group_start
        {_, 3} ->
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        % 4 = group_end
        {_, 4} ->
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        % 5 = bits32
        {_, 5} ->
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum) when
    N < (64 - 7)
->
    read_gr_vi(Tl, N + 7, NumBytes + 1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes + 1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) when
    N < (64 - 7)
->
    read_gr_ld(Tl, N + 7, X bsl N + Acc, NumBytes + 1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New) when element(1, Prev) =:= element(1, New) ->
    merge_msgs(Prev, New, element(1, Prev), []).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) -> merge_msgs(Prev, New, MsgName, []);
merge_msgs(Prev, New, Opts) when element(1, Prev) =:= element(1, New), is_list(Opts) ->
    merge_msgs(Prev, New, element(1, Prev), Opts).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'eventssidecar.v1.OnClientOffline' ->
            'merge_msg_eventssidecar.v1.OnClientOffline'(Prev, New, TrUserData);
        'google.protobuf.Timestamp' ->
            'merge_msg_google.protobuf.Timestamp'(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function, 'merge_msg_eventssidecar.v1.OnClientOffline'/3}).
'merge_msg_eventssidecar.v1.OnClientOffline'(
    #'eventssidecar.v1.OnClientOffline'{
        timestamp = PFtimestamp,
        client_id = PFclient_id,
        mountpoint = PFmountpoint,
        reason = PFreason
    },
    #'eventssidecar.v1.OnClientOffline'{
        timestamp = NFtimestamp,
        client_id = NFclient_id,
        mountpoint = NFmountpoint,
        reason = NFreason
    },
    TrUserData
) ->
    #'eventssidecar.v1.OnClientOffline'{
        timestamp =
            if
                PFtimestamp /= undefined, NFtimestamp /= undefined ->
                    'merge_msg_google.protobuf.Timestamp'(PFtimestamp, NFtimestamp, TrUserData);
                PFtimestamp == undefined ->
                    NFtimestamp;
                NFtimestamp == undefined ->
                    PFtimestamp
            end,
        client_id =
            if
                NFclient_id =:= undefined -> PFclient_id;
                true -> NFclient_id
            end,
        mountpoint =
            if
                NFmountpoint =:= undefined -> PFmountpoint;
                true -> NFmountpoint
            end,
        reason =
            if
                NFreason =:= undefined -> PFreason;
                true -> NFreason
            end
    }.

-compile({nowarn_unused_function, 'merge_msg_google.protobuf.Timestamp'/3}).
'merge_msg_google.protobuf.Timestamp'(
    #'google.protobuf.Timestamp'{seconds = PFseconds, nanos = PFnanos},
    #'google.protobuf.Timestamp'{seconds = NFseconds, nanos = NFnanos},
    _
) ->
    #'google.protobuf.Timestamp'{
        seconds =
            if
                NFseconds =:= undefined -> PFseconds;
                true -> NFseconds
            end,
        nanos =
            if
                NFnanos =:= undefined -> PFnanos;
                true -> NFnanos
            end
    }.

verify_msg(Msg) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), []);
verify_msg(X) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName) when is_atom(MsgName) -> verify_msg(Msg, MsgName, []);
verify_msg(Msg, Opts) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), Opts);
verify_msg(X, _Opts) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'eventssidecar.v1.OnClientOffline' ->
            'v_msg_eventssidecar.v1.OnClientOffline'(Msg, [MsgName], TrUserData);
        'google.protobuf.Timestamp' ->
            'v_msg_google.protobuf.Timestamp'(Msg, [MsgName], TrUserData);
        _ ->
            mk_type_error(not_a_known_message, Msg, [])
    end.

-compile({nowarn_unused_function, 'v_msg_eventssidecar.v1.OnClientOffline'/3}).
-dialyzer({nowarn_function, 'v_msg_eventssidecar.v1.OnClientOffline'/3}).
'v_msg_eventssidecar.v1.OnClientOffline'(
    #'eventssidecar.v1.OnClientOffline'{
        timestamp = F1, client_id = F2, mountpoint = F3, reason = F4
    },
    Path,
    TrUserData
) ->
    if
        F1 == undefined -> ok;
        true -> 'v_submsg_google.protobuf.Timestamp'(F1, [timestamp | Path], TrUserData)
    end,
    if
        F2 == undefined -> ok;
        true -> v_type_string(F2, [client_id | Path], TrUserData)
    end,
    if
        F3 == undefined -> ok;
        true -> v_type_string(F3, [mountpoint | Path], TrUserData)
    end,
    if
        F4 == undefined -> ok;
        true -> 'v_enum_eventssidecar.v1.Reason'(F4, [reason | Path], TrUserData)
    end,
    ok;
'v_msg_eventssidecar.v1.OnClientOffline'(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, 'eventssidecar.v1.OnClientOffline'}, X, Path).

-compile({nowarn_unused_function, 'v_submsg_google.protobuf.Timestamp'/3}).
-dialyzer({nowarn_function, 'v_submsg_google.protobuf.Timestamp'/3}).
'v_submsg_google.protobuf.Timestamp'(Msg, Path, TrUserData) ->
    'v_msg_google.protobuf.Timestamp'(Msg, Path, TrUserData).

-compile({nowarn_unused_function, 'v_msg_google.protobuf.Timestamp'/3}).
-dialyzer({nowarn_function, 'v_msg_google.protobuf.Timestamp'/3}).
'v_msg_google.protobuf.Timestamp'(
    #'google.protobuf.Timestamp'{seconds = F1, nanos = F2}, Path, TrUserData
) ->
    if
        F1 == undefined -> ok;
        true -> v_type_int64(F1, [seconds | Path], TrUserData)
    end,
    if
        F2 == undefined -> ok;
        true -> v_type_int32(F2, [nanos | Path], TrUserData)
    end,
    ok;
'v_msg_google.protobuf.Timestamp'(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, 'google.protobuf.Timestamp'}, X, Path).

-compile({nowarn_unused_function, 'v_enum_eventssidecar.v1.Reason'/3}).
-dialyzer({nowarn_function, 'v_enum_eventssidecar.v1.Reason'/3}).
'v_enum_eventssidecar.v1.Reason'('REASON_UNSPECIFIED', _Path, _TrUserData) ->
    ok;
'v_enum_eventssidecar.v1.Reason'('REASON_NOT_AUTHORIZED', _Path, _TrUserData) ->
    ok;
'v_enum_eventssidecar.v1.Reason'('REASON_NORMAL_DISCONNECT', _Path, _TrUserData) ->
    ok;
'v_enum_eventssidecar.v1.Reason'('REASON_SESSION_TAKEN_OVER', _Path, _TrUserData) ->
    ok;
'v_enum_eventssidecar.v1.Reason'('REASON_ADMINISTRATIVE_ACTION', _Path, _TrUserData) ->
    ok;
'v_enum_eventssidecar.v1.Reason'('REASON_DISCONNECT_KEEP_ALIVE', _Path, _TrUserData) ->
    ok;
'v_enum_eventssidecar.v1.Reason'('REASON_DISCONNECT_MIGRATION', _Path, _TrUserData) ->
    ok;
'v_enum_eventssidecar.v1.Reason'('REASON_BAD_AUTHENTICATION_METHOD', _Path, _TrUserData) ->
    ok;
'v_enum_eventssidecar.v1.Reason'('REASON_REMOTE_SESSION_TAKEN_OVER', _Path, _TrUserData) ->
    ok;
'v_enum_eventssidecar.v1.Reason'('REASON_MQTT_CLIENT_DISCONNECT', _Path, _TrUserData) ->
    ok;
'v_enum_eventssidecar.v1.Reason'('REASON_RECEIVE_MAX_EXCEEDED', _Path, _TrUserData) ->
    ok;
'v_enum_eventssidecar.v1.Reason'('REASON_PROTOCOL_ERROR', _Path, _TrUserData) ->
    ok;
'v_enum_eventssidecar.v1.Reason'('REASON_PUBLISH_AUTH_ERROR', _Path, _TrUserData) ->
    ok;
'v_enum_eventssidecar.v1.Reason'('REASON_INVALID_PUBREC_ERROR', _Path, _TrUserData) ->
    ok;
'v_enum_eventssidecar.v1.Reason'('REASON_INVALID_PUBCOMP_ERROR', _Path, _TrUserData) ->
    ok;
'v_enum_eventssidecar.v1.Reason'('REASON_UNEXPECTED_FRAME_TYPE', _Path, _TrUserData) ->
    ok;
'v_enum_eventssidecar.v1.Reason'('REASON_EXIT_SIGNAL_RECEIVED', _Path, _TrUserData) ->
    ok;
'v_enum_eventssidecar.v1.Reason'('REASON_TCP_CLOSED', _Path, _TrUserData) ->
    ok;
'v_enum_eventssidecar.v1.Reason'(V, _Path, _TrUserData) when
    -2147483648 =< V, V =< 2147483647, is_integer(V)
->
    ok;
'v_enum_eventssidecar.v1.Reason'(X, Path, _TrUserData) ->
    mk_type_error({invalid_enum, 'eventssidecar.v1.Reason'}, X, Path).

-compile({nowarn_unused_function, v_type_int32/3}).
-dialyzer({nowarn_function, v_type_int32/3}).
v_type_int32(N, _Path, _TrUserData) when is_integer(N), -2147483648 =< N, N =< 2147483647 -> ok;
v_type_int32(N, Path, _TrUserData) when is_integer(N) ->
    mk_type_error({value_out_of_range, int32, signed, 32}, N, Path);
v_type_int32(X, Path, _TrUserData) ->
    mk_type_error({bad_integer, int32, signed, 32}, X, Path).

-compile({nowarn_unused_function, v_type_int64/3}).
-dialyzer({nowarn_function, v_type_int64/3}).
v_type_int64(N, _Path, _TrUserData) when
    is_integer(N), -9223372036854775808 =< N, N =< 9223372036854775807
->
    ok;
v_type_int64(N, Path, _TrUserData) when is_integer(N) ->
    mk_type_error({value_out_of_range, int64, signed, 64}, N, Path);
v_type_int64(X, Path, _TrUserData) ->
    mk_type_error({bad_integer, int64, signed, 64}, X, Path).

-compile({nowarn_unused_function, v_type_string/3}).
-dialyzer({nowarn_function, v_type_string/3}).
v_type_string(S, Path, _TrUserData) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
        B when is_binary(B) -> ok;
        {error, _, _} -> mk_type_error(bad_unicode_string, S, Path)
    catch
        error:badarg -> mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) ->
    mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function, mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error, {Error, [{value, ValueSeen}, {path, Path2}]}}).

-compile({nowarn_unused_function, prettify_path/1}).
-dialyzer({nowarn_function, prettify_path/1}).
prettify_path([]) ->
    top_level;
prettify_path(PathR) ->
    lists:append(lists:join(".", lists:map(fun atom_to_list/1, lists:reverse(PathR)))).

-compile({nowarn_unused_function, id/2}).
-compile({inline, id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function, v_ok/3}).
-compile({inline, v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function, m_overwrite/3}).
-compile({inline, m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function, cons/3}).
-compile({inline, cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function, lists_reverse/2}).
-compile({inline, lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function, 'erlang_++'/3}).
-compile({inline, 'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.

get_msg_defs() ->
    [
        {{enum, 'eventssidecar.v1.Reason'}, [
            {'REASON_UNSPECIFIED', 0},
            {'REASON_NOT_AUTHORIZED', 1},
            {'REASON_NORMAL_DISCONNECT', 2},
            {'REASON_SESSION_TAKEN_OVER', 3},
            {'REASON_ADMINISTRATIVE_ACTION', 4},
            {'REASON_DISCONNECT_KEEP_ALIVE', 5},
            {'REASON_DISCONNECT_MIGRATION', 6},
            {'REASON_BAD_AUTHENTICATION_METHOD', 7},
            {'REASON_REMOTE_SESSION_TAKEN_OVER', 8},
            {'REASON_MQTT_CLIENT_DISCONNECT', 9},
            {'REASON_RECEIVE_MAX_EXCEEDED', 10},
            {'REASON_PROTOCOL_ERROR', 11},
            {'REASON_PUBLISH_AUTH_ERROR', 12},
            {'REASON_INVALID_PUBREC_ERROR', 13},
            {'REASON_INVALID_PUBCOMP_ERROR', 14},
            {'REASON_UNEXPECTED_FRAME_TYPE', 15},
            {'REASON_EXIT_SIGNAL_RECEIVED', 16},
            {'REASON_TCP_CLOSED', 17}
        ]},
        {{msg, 'eventssidecar.v1.OnClientOffline'}, [
            #field{
                name = timestamp,
                fnum = 1,
                rnum = 2,
                type = {msg, 'google.protobuf.Timestamp'},
                occurrence = optional,
                opts = []
            },
            #field{
                name = client_id,
                fnum = 2,
                rnum = 3,
                type = string,
                occurrence = optional,
                opts = []
            },
            #field{
                name = mountpoint,
                fnum = 3,
                rnum = 4,
                type = string,
                occurrence = optional,
                opts = []
            },
            #field{
                name = reason,
                fnum = 4,
                rnum = 5,
                type = {enum, 'eventssidecar.v1.Reason'},
                occurrence = optional,
                opts = []
            }
        ]},
        {{msg, 'google.protobuf.Timestamp'}, [
            #field{
                name = seconds, fnum = 1, rnum = 2, type = int64, occurrence = optional, opts = []
            },
            #field{name = nanos, fnum = 2, rnum = 3, type = int32, occurrence = optional, opts = []}
        ]}
    ].

get_msg_names() -> ['eventssidecar.v1.OnClientOffline', 'google.protobuf.Timestamp'].

get_group_names() -> [].

get_msg_or_group_names() -> ['eventssidecar.v1.OnClientOffline', 'google.protobuf.Timestamp'].

get_enum_names() -> ['eventssidecar.v1.Reason'].

fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
        Fs when is_list(Fs) -> Fs;
        error -> erlang:error({no_such_msg, MsgName})
    end.

fetch_enum_def(EnumName) ->
    case find_enum_def(EnumName) of
        Es when is_list(Es) -> Es;
        error -> erlang:error({no_such_enum, EnumName})
    end.

find_msg_def('eventssidecar.v1.OnClientOffline') ->
    [
        #field{
            name = timestamp,
            fnum = 1,
            rnum = 2,
            type = {msg, 'google.protobuf.Timestamp'},
            occurrence = optional,
            opts = []
        },
        #field{
            name = client_id, fnum = 2, rnum = 3, type = string, occurrence = optional, opts = []
        },
        #field{
            name = mountpoint, fnum = 3, rnum = 4, type = string, occurrence = optional, opts = []
        },
        #field{
            name = reason,
            fnum = 4,
            rnum = 5,
            type = {enum, 'eventssidecar.v1.Reason'},
            occurrence = optional,
            opts = []
        }
    ];
find_msg_def('google.protobuf.Timestamp') ->
    [
        #field{name = seconds, fnum = 1, rnum = 2, type = int64, occurrence = optional, opts = []},
        #field{name = nanos, fnum = 2, rnum = 3, type = int32, occurrence = optional, opts = []}
    ];
find_msg_def(_) ->
    error.

find_enum_def('eventssidecar.v1.Reason') ->
    [
        {'REASON_UNSPECIFIED', 0},
        {'REASON_NOT_AUTHORIZED', 1},
        {'REASON_NORMAL_DISCONNECT', 2},
        {'REASON_SESSION_TAKEN_OVER', 3},
        {'REASON_ADMINISTRATIVE_ACTION', 4},
        {'REASON_DISCONNECT_KEEP_ALIVE', 5},
        {'REASON_DISCONNECT_MIGRATION', 6},
        {'REASON_BAD_AUTHENTICATION_METHOD', 7},
        {'REASON_REMOTE_SESSION_TAKEN_OVER', 8},
        {'REASON_MQTT_CLIENT_DISCONNECT', 9},
        {'REASON_RECEIVE_MAX_EXCEEDED', 10},
        {'REASON_PROTOCOL_ERROR', 11},
        {'REASON_PUBLISH_AUTH_ERROR', 12},
        {'REASON_INVALID_PUBREC_ERROR', 13},
        {'REASON_INVALID_PUBCOMP_ERROR', 14},
        {'REASON_UNEXPECTED_FRAME_TYPE', 15},
        {'REASON_EXIT_SIGNAL_RECEIVED', 16},
        {'REASON_TCP_CLOSED', 17}
    ];
find_enum_def(_) ->
    error.

enum_symbol_by_value('eventssidecar.v1.Reason', Value) ->
    'enum_symbol_by_value_eventssidecar.v1.Reason'(Value).

enum_value_by_symbol('eventssidecar.v1.Reason', Sym) ->
    'enum_value_by_symbol_eventssidecar.v1.Reason'(Sym).

'enum_symbol_by_value_eventssidecar.v1.Reason'(0) -> 'REASON_UNSPECIFIED';
'enum_symbol_by_value_eventssidecar.v1.Reason'(1) -> 'REASON_NOT_AUTHORIZED';
'enum_symbol_by_value_eventssidecar.v1.Reason'(2) -> 'REASON_NORMAL_DISCONNECT';
'enum_symbol_by_value_eventssidecar.v1.Reason'(3) -> 'REASON_SESSION_TAKEN_OVER';
'enum_symbol_by_value_eventssidecar.v1.Reason'(4) -> 'REASON_ADMINISTRATIVE_ACTION';
'enum_symbol_by_value_eventssidecar.v1.Reason'(5) -> 'REASON_DISCONNECT_KEEP_ALIVE';
'enum_symbol_by_value_eventssidecar.v1.Reason'(6) -> 'REASON_DISCONNECT_MIGRATION';
'enum_symbol_by_value_eventssidecar.v1.Reason'(7) -> 'REASON_BAD_AUTHENTICATION_METHOD';
'enum_symbol_by_value_eventssidecar.v1.Reason'(8) -> 'REASON_REMOTE_SESSION_TAKEN_OVER';
'enum_symbol_by_value_eventssidecar.v1.Reason'(9) -> 'REASON_MQTT_CLIENT_DISCONNECT';
'enum_symbol_by_value_eventssidecar.v1.Reason'(10) -> 'REASON_RECEIVE_MAX_EXCEEDED';
'enum_symbol_by_value_eventssidecar.v1.Reason'(11) -> 'REASON_PROTOCOL_ERROR';
'enum_symbol_by_value_eventssidecar.v1.Reason'(12) -> 'REASON_PUBLISH_AUTH_ERROR';
'enum_symbol_by_value_eventssidecar.v1.Reason'(13) -> 'REASON_INVALID_PUBREC_ERROR';
'enum_symbol_by_value_eventssidecar.v1.Reason'(14) -> 'REASON_INVALID_PUBCOMP_ERROR';
'enum_symbol_by_value_eventssidecar.v1.Reason'(15) -> 'REASON_UNEXPECTED_FRAME_TYPE';
'enum_symbol_by_value_eventssidecar.v1.Reason'(16) -> 'REASON_EXIT_SIGNAL_RECEIVED';
'enum_symbol_by_value_eventssidecar.v1.Reason'(17) -> 'REASON_TCP_CLOSED'.

'enum_value_by_symbol_eventssidecar.v1.Reason'('REASON_UNSPECIFIED') -> 0;
'enum_value_by_symbol_eventssidecar.v1.Reason'('REASON_NOT_AUTHORIZED') -> 1;
'enum_value_by_symbol_eventssidecar.v1.Reason'('REASON_NORMAL_DISCONNECT') -> 2;
'enum_value_by_symbol_eventssidecar.v1.Reason'('REASON_SESSION_TAKEN_OVER') -> 3;
'enum_value_by_symbol_eventssidecar.v1.Reason'('REASON_ADMINISTRATIVE_ACTION') -> 4;
'enum_value_by_symbol_eventssidecar.v1.Reason'('REASON_DISCONNECT_KEEP_ALIVE') -> 5;
'enum_value_by_symbol_eventssidecar.v1.Reason'('REASON_DISCONNECT_MIGRATION') -> 6;
'enum_value_by_symbol_eventssidecar.v1.Reason'('REASON_BAD_AUTHENTICATION_METHOD') -> 7;
'enum_value_by_symbol_eventssidecar.v1.Reason'('REASON_REMOTE_SESSION_TAKEN_OVER') -> 8;
'enum_value_by_symbol_eventssidecar.v1.Reason'('REASON_MQTT_CLIENT_DISCONNECT') -> 9;
'enum_value_by_symbol_eventssidecar.v1.Reason'('REASON_RECEIVE_MAX_EXCEEDED') -> 10;
'enum_value_by_symbol_eventssidecar.v1.Reason'('REASON_PROTOCOL_ERROR') -> 11;
'enum_value_by_symbol_eventssidecar.v1.Reason'('REASON_PUBLISH_AUTH_ERROR') -> 12;
'enum_value_by_symbol_eventssidecar.v1.Reason'('REASON_INVALID_PUBREC_ERROR') -> 13;
'enum_value_by_symbol_eventssidecar.v1.Reason'('REASON_INVALID_PUBCOMP_ERROR') -> 14;
'enum_value_by_symbol_eventssidecar.v1.Reason'('REASON_UNEXPECTED_FRAME_TYPE') -> 15;
'enum_value_by_symbol_eventssidecar.v1.Reason'('REASON_EXIT_SIGNAL_RECEIVED') -> 16;
'enum_value_by_symbol_eventssidecar.v1.Reason'('REASON_TCP_CLOSED') -> 17.

get_service_names() -> [].

get_service_def(_) -> error.

get_rpc_names(_) -> error.

find_rpc_def(_, _) -> error.

-spec fetch_rpc_def(_, _) -> no_return().
fetch_rpc_def(ServiceName, RpcName) -> erlang:error({no_such_rpc, ServiceName, RpcName}).

%% Convert a a fully qualified (ie with package name) service name
%% as a binary to a service name as an atom.
-spec fqbin_to_service_name(_) -> no_return().
fqbin_to_service_name(X) -> error({gpb_error, {badservice, X}}).

%% Convert a service name as an atom to a fully qualified
%% (ie with package name) name as a binary.
-spec service_name_to_fqbin(_) -> no_return().
service_name_to_fqbin(X) -> error({gpb_error, {badservice, X}}).

%% Convert a a fully qualified (ie with package name) service name
%% and an rpc name, both as binaries to a service name and an rpc
%% name, as atoms.
-spec fqbins_to_service_and_rpc_name(_, _) -> no_return().
fqbins_to_service_and_rpc_name(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).

%% Convert a service name and an rpc name, both as atoms,
%% to a fully qualified (ie with package name) service name and
%% an rpc name as binaries.
-spec service_and_rpc_name_to_fqbins(_, _) -> no_return().
service_and_rpc_name_to_fqbins(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).

fqbin_to_msg_name(<<"eventssidecar.v1.OnClientOffline">>) -> 'eventssidecar.v1.OnClientOffline';
fqbin_to_msg_name(<<"google.protobuf.Timestamp">>) -> 'google.protobuf.Timestamp';
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).

msg_name_to_fqbin('eventssidecar.v1.OnClientOffline') -> <<"eventssidecar.v1.OnClientOffline">>;
msg_name_to_fqbin('google.protobuf.Timestamp') -> <<"google.protobuf.Timestamp">>;
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).

fqbin_to_enum_name(<<"eventssidecar.v1.Reason">>) -> 'eventssidecar.v1.Reason';
fqbin_to_enum_name(E) -> error({gpb_error, {badenum, E}}).

enum_name_to_fqbin('eventssidecar.v1.Reason') -> <<"eventssidecar.v1.Reason">>;
enum_name_to_fqbin(E) -> error({gpb_error, {badenum, E}}).

get_package_name() -> 'eventssidecar.v1'.

%% Whether or not the message names
%% are prepended with package name or not.
uses_packages() -> true.

source_basename() -> "on_client_offline.proto".

%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned with extension,
%% see get_all_proto_names/0 for a version that returns
%% the basenames sans extension
get_all_source_basenames() ->
    ["on_client_offline.proto", "timestamp.proto", "disconnect_reason.proto"].

%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned sans .proto extension,
%% to make it easier to use them with the various get_xyz_containment
%% functions.
get_all_proto_names() -> ["on_client_offline", "timestamp", "disconnect_reason"].

get_msg_containment("on_client_offline") -> ['eventssidecar.v1.OnClientOffline'];
get_msg_containment("timestamp") -> ['google.protobuf.Timestamp'];
get_msg_containment("disconnect_reason") -> [];
get_msg_containment(P) -> error({gpb_error, {badproto, P}}).

get_pkg_containment("on_client_offline") -> 'eventssidecar.v1';
get_pkg_containment("timestamp") -> 'google.protobuf';
get_pkg_containment("disconnect_reason") -> 'eventssidecar.v1';
get_pkg_containment(P) -> error({gpb_error, {badproto, P}}).

get_service_containment("on_client_offline") -> [];
get_service_containment("timestamp") -> [];
get_service_containment("disconnect_reason") -> [];
get_service_containment(P) -> error({gpb_error, {badproto, P}}).

get_rpc_containment("on_client_offline") -> [];
get_rpc_containment("timestamp") -> [];
get_rpc_containment("disconnect_reason") -> [];
get_rpc_containment(P) -> error({gpb_error, {badproto, P}}).

get_enum_containment("on_client_offline") -> [];
get_enum_containment("timestamp") -> [];
get_enum_containment("disconnect_reason") -> ['eventssidecar.v1.Reason'];
get_enum_containment(P) -> error({gpb_error, {badproto, P}}).

get_proto_by_msg_name_as_fqbin(<<"google.protobuf.Timestamp">>) -> "timestamp";
get_proto_by_msg_name_as_fqbin(<<"eventssidecar.v1.OnClientOffline">>) -> "on_client_offline";
get_proto_by_msg_name_as_fqbin(E) -> error({gpb_error, {badmsg, E}}).

-spec get_proto_by_service_name_as_fqbin(_) -> no_return().
get_proto_by_service_name_as_fqbin(E) -> error({gpb_error, {badservice, E}}).

get_proto_by_enum_name_as_fqbin(<<"eventssidecar.v1.Reason">>) -> "disconnect_reason";
get_proto_by_enum_name_as_fqbin(E) -> error({gpb_error, {badenum, E}}).

get_protos_by_pkg_name_as_fqbin(<<"eventssidecar.v1">>) ->
    ["disconnect_reason", "on_client_offline"];
get_protos_by_pkg_name_as_fqbin(<<"google.protobuf">>) ->
    ["timestamp"];
get_protos_by_pkg_name_as_fqbin(E) ->
    error({gpb_error, {badpkg, E}}).

gpb_version_as_string() ->
    "4.20.0".

gpb_version_as_list() ->
    [4, 20, 0].

gpb_version_source() ->
    "file".
