#! /bin/sh
# postinst script for vernemq

# create group
if ! getent group vernemq >/dev/null; then
  addgroup --system vernemq
fi

# create user
if ! getent passwd vernemq >/dev/null; then
  adduser --ingroup vernemq \
          --home /var/lib/vernemq \
          --disabled-password \
          --system --shell /bin/bash --no-create-home \
          --gecos "VerneMQ broker" vernemq
fi

for i in lib log; do
    chown -R vernemq:vernemq /var/$i/vernemq
done
