#!/bin/env python


copyright = """%% Copyright 2019 Octavo Labs AG Switzerland (https://vernemq.com)
%%
%% Licensed under the Apache License, Version 2.0 (the "License");
%% you may not use this file except in compliance with the License.
%% You may obtain a copy of the License at
%%
%%     http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing, software
%% distributed under the License is distributed on an "AS IS" BASIS,
%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%% See the License for the specific language governing permissions and
%% limitations under the License.


%% !! This module is autogenerated with generate_pick_random.py

"""

# Optimize for lists smaller than `n_opt`
n_opt = 32

# Erlang module name
module_name = "pick_random"


api_fun = """
pick_random(_Fun, Acc, []) -> Acc;
pick_random(Fun, Acc0, List) ->
  L = length(List),
  case L > %s of
    false ->
      apply(?MODULE, pick_random_, [Fun, Acc0, rand:uniform(L) | List]);
    true ->
      try
        lists:foldl(fun({_, E}, AccAcc0) ->
                      case Fun(E, AccAcc0) of
                        {ok, AccAcc1} ->
                          throw({done, AccAcc1});
                        AccAcc1 ->
                          AccAcc1
                      end
                    end, Acc0, lists:keysort(1, [{rand:uniform(), E} || E <- List]))
      catch
        {done, Acc1} -> Acc1
      end
  end.

"""

def write_module(f):
    f.write(copyright)
    f.write("-module(" + module_name + ").\n")
    f.write("-export([\n")
    f.write("  pick_random/3\n")

    for i in range(1, n_opt + 1):
        f.write("  , pick_random_/" + str(i + 3) + "\n")
    f.write("  ]).\n\n")

    f.write(api_fun % n_opt)

    f.write("pick_random_(_, {ok, Acc}) -> Acc;\n")
    f.write("pick_random_(_, Acc) -> Acc.\n\n")

    for i in range(1, n_opt + 1):
        s = "_"
        for t in range(1, i + 1):
            s = s + ", _"

        f.write("pick_random_(_, {ok, Acc}, " + s + ") -> Acc;\n")

        for t in range(1, i + 1):
            s = ""
            for tt in range(1, i + 1):
                s = s + ", E" + str(tt)

            f.write("pick_random_(Fun, Acc, " + str(t) + s + ") ->\n")
            s = ""
            for tt in range(1, i + 1):
                if tt != t:
                    s = s + ", E" + str(tt)
            eol = ";\n"
            if t == i:
                eol = ".\n\n"

            if i == 1:
                f.write("  pick_random_(Fun, Fun(E" + str(t) + ", Acc))" + eol)
            else:
                f.write("  pick_random_(Fun, Fun(E" + str(t) + ", Acc), rand:uniform(" + str(i - 1) + ")" + s + ")" + eol)

f = open(module_name + ".erl", "w+")
write_module(f)

