%% Test helpers
-define(PEER_BIN, <<"127.0.0.1">>).
-define(PEERPORT, 12345).
-define(PEER, {{127,0,0,1}, ?PEERPORT}).
-define(ALLOWED_CLIENT_ID, <<"allowed-subscriber-id">>).
-define(MOUNTPOINT, "mountpoint").
-define(MOUNTPOINT_BIN, <<"mountpoint">>).
-define(TOPIC, <<"test/topic">>).
-define(PAYLOAD, <<"hello world">>).
-define(REASON, 'REASON_NORMAL_DISCONNECT').
-define(LABEL, <<"test-label">>).
-define(PATTERN, <<"test/pattern">>).
-define(MESSAGE_DROP_REASON, <<"queue_full">>).
-define(SESSION_ID, <<"96366244-e848-4ef4-82c1-5ee7c5cf8102">>).
